name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # Run unit tests using pytest
      - name: Run unit tests with pytest
        run: pytest tests/
