name: CI/CD Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: spheric-engine-451615-a8
          install_components: 'gcloud'

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/spheric-engine-451615-a8/sellercentral-chatbot:$GITHUB_SHA .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/spheric-engine-451615-a8/sellercentral-chatbot:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sellercentral-chatbot \
            --image gcr.io/spheric-engine-451615-a8/sellercentral-chatbot:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 4Gi \
            --timeout 300 \
            --set-env-vars "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},HF_TOKEN=${{ secrets.HF_TOKEN }},GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }},LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }},LANGFUSE_HOST=${{ secrets.LANGFUSE_HOST }}" \
            --service-account 1061880689774-compute@developer.gserviceaccount.com
