name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: spheric-engine-451615-a8
  SERVICE: chatbot-apiv2
  REGION: us-central1

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate to Google Cloud using a service account key stored in GitHub Secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 4Gi \
            --timeout 300 \
            --service-account 1061880689774-compute@developer.gserviceaccount.com \
            --set-secrets "HF_TOKEN=HF_TOKEN:latest" \
            --set-secrets "DEEPSEEK_API_KEY=DEEPSEEK_API_KEY:latest" \
            --set-secrets "LANGFUSE_PUBLIC_KEY=LANGFUSE_PUBLIC_KEY:latest" \
            --set-secrets "LANGFUSE_SECRET_KEY=LANGFUSE_SECRET_KEY:latest" \
            --set-secrets "OPENAI_API_KEY=OPENAI_API_KEY:latest" \
            --set-secrets "GROQ_API_KEY=GROQ_API_KEY:latest" \
            --set-secrets "LANGFUSE_HOST=LANGFUSE_HOST:latest" \
            --set-secrets "GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS:latest"
