name: Build and Deploy to Cloud Run
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker image
        env:
          IMAGE_NAME: sellercentral-chatbot
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          TAG: ${{ github.sha }}
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG .
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$TAG

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud run deploy sellercentral-chatbot \
            --image gcr.io/$PROJECT_ID/sellercentral-chatbot:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --memory 4Gi \
            --timeout 300 \
            --service-account ${{ secrets.CLOUDRUN_SA_EMAIL }} \
            --set-env-vars DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }},\
                            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},\
                            HF_TOKEN=${{ secrets.HF_TOKEN }},\
                            GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},\
                            LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }},\
                            LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }},\
                            LANGFUSE_HOST=${{ secrets.LANGFUSE_HOST }},\
                            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
