name: Run Model Evaluation 

on:
  push:
    branches:
      - main
    paths:
      - 'model_evaluation/**'
      - '.github/workflows/Model_Evaluation.yml'
  workflow_dispatch:

env:
  PROJECT_ID: spheric-engine-451615-a8
  SERVICE: chatbot-apiv2
  REGION: us-central1

jobs:
  evaluate-model:
    name: Run Model Evaluation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Authenticate to Google Cloud using a service account key stored in GitHub Secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image for model evaluation
        working-directory: model_evaluation
        run: docker build -t model-eval-image:latest .

      - name: Run model evaluation container
        run: >
          docker run --rm
          -e HF_TOKEN=${{ secrets.HF_TOKEN }}
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          -e DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          -e LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}
          -e LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}
          -e LANGFUSE_HOST=${{ secrets.LANGFUSE_HOST }}
          -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          model-eval-image:latest
