name: Run Model Evaluation 

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: spheric-engine-451615-a8
  SERVICE: chatbot-apiv2
  REGION: us-central1

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Authenticate to Google Cloud using a service account key stored in GitHub Secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t kavi963/chatbot_evaluation:latest .

      - name: Push Docker Image
        run: |
          docker push kavi963/chatbot_evaluation:latest
