name: Run Model Evaluation 

on:
  push:
    branches:
      - main
    paths:
      - 'model_evaluation/**'
      - '.github/workflows/Model_Evaluation.yml'
  workflow_dispatch:

env:
  PROJECT_ID: spheric-engine-451615-a8
  SERVICE: chatbot-apiv2
  REGION: us-central1

jobs:
  evaluate-model:
    name: Run Model Evaluation
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: model_evaluation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Authenticate to Google Cloud using a service account key stored in GitHub Secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Inject GCP credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > model_evaluation/service_account.json

      - name: Build Docker image for model evaluation
        run: docker build -t model-eval-image .

      - name: Run model evaluation container
        run: docker run --rm model-eval-image
